/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as singleSwapSol from "./SingleSwap.sol";
export type { singleSwapSol };
import type * as interfaces from "./interfaces";
export type { interfaces };
