/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as erc20BooSol from "./ERC20Boo.sol";
export type { erc20BooSol };
import type * as erc20LifeSol from "./ERC20Life.sol";
export type { erc20LifeSol };
import type * as liquditySol from "./Liqudity.sol";
export type { liquditySol };
import type * as swapTokenSol from "./SwapToken.sol";
export type { swapTokenSol };
import type * as interfaces from "./interfaces";
export type { interfaces };
export type { SwapMultiHop } from "./SwapMultiHop";
